import turtle

dakua_turtle = turtle.Turtle() #CREATE OBJECT
dakua_turtle.speed(15)

def squre():   #FUNCTION 
  dakua_turtle.forward(25)
  dakua_turtle.right(90)
  dakua_turtle.forward(25)
  dakua_turtle.right(90)
  dakua_turtle.forward(25)
  dakua_turtle.right(90)
  dakua_turtle.forward(35)
  dakua_turtle.right(90)
  dakua_turtle.forward(35)
  dakua_turtle.right(90)
  dakua_turtle.forward(45)
  dakua_turtle.right(90)
  dakua_turtle.forward(45)
  dakua_turtle.right(90)
  dakua_turtle.forward(55)
  dakua_turtle.right(90)
  dakua_turtle.forward(55)
  dakua_turtle.right(90)
  dakua_turtle.forward(65)
  dakua_turtle.right(90)
  dakua_turtle.forward(65)
  dakua_turtle.right(90)
  dakua_turtle.forward(75)
  dakua_turtle.right(90)
  dakua_turtle.forward(75)
  dakua_turtle.right(90)
  dakua_turtle.forward(85)
  dakua_turtle.right(90)
  dakua_turtle.forward(85)
  dakua_turtle.right(90)
  dakua_turtle.forward(95)
  dakua_turtle.right(90)
  dakua_turtle.forward(95)
  dakua_turtle.right(90)
  dakua_turtle.forward(105)
  dakua_turtle.right(90)
  dakua_turtle.forward(105)
  dakua_turtle.right(90)
  dakua_turtle.forward(115)
  dakua_turtle.right(90)
  dakua_turtle.forward(115)
  dakua_turtle.right(90)
  dakua_turtle.forward(125)
  dakua_turtle.right(90)
  dakua_turtle.forward(125)
  dakua_turtle.right(135)
  dakua_turtle.forward(190.92)


squre()
dakua_turtle.forward(50)
squre()
dakua_turtle.left(90)
dakua_turtle.forward(135)
squre()
dakua_turtle.forward(50)
squre()
dakua_turtle.left(45)
dakua_turtle.forward(135)
